### ISSUE TITLE
Loss of window focus causes duplicate check for installed components

### ISSUE THREAD

**Issue by robin-owen** [redhat-developer-tooling/developer-platform-install#1094] opened 2017-12-05 22:18 UTC
I'm not sure if this is working as intended or if this is a bug.

On Windows 10, if the installer loses focus for any reason (tested using the Windows start menu, alt+tab window switching, and clicking on the desktop), the installer will re-run the check for already-installed components.

The only use case I can personally think of where this would be desired is if a component happens to be installed while the installer itself is running -- this seems rather unlikely. It's far more likely that the user will lose focus for some other reason and have to come back to the installer to have it run a check that it has already run before.

Note that this check will occur as often as focus on the window is lost and then regained.

**Comment by dgolovin** [comment] 2017-12-06 08:50
Thank you for reporting this problem. It is working as intended and was originally added to address specific use cases. For example, let's say you have old Virtualbox version detected, that would not work with CDK. Installer would not let you continue with CDK installation until this issue is fixed by removing it. You would switch to control panel and uninstall Virtualbox. On returning to installer window detection is triggered, no Virtualbox is detected and you can continue with installation.

It turned out detection is very slow on windows specifically for OpenJDK installation. **we are planning to address this issue** by making duplicate check for installed components extremely fast. It would just check if components detected on first check where removed during the time installer window lost its focus. That would cover use case above and make secon detection run barely noticeable.

**Comment by dgolovin** [comment] 2017-12-08 07:49
This is also reported here https://issues.jboss.org/browse/JBDS-4402.

**Comment by dgolovin** [comment] 2018-03-28 05:34
Detection performance was improved, now after window lost and got focus back, detection takes less than second.

**Closed by dgolovin** 2018-03-28 05:34 UTC
Labels: kind/bug, priority/major
